In [1]:
import tensorflow as tf

In [2]:
tf.set_random_seed(777)

In [3]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [4]:
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [5]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

In [6]:
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [13]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [14]:
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.argmax(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [15]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
    
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    print("Accuracy:", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 5.7320304 [[ 0.8026957  0.6786129 -1.2172831]
 [-0.3051686 -0.3032113  1.508257 ]
 [ 0.7572236 -0.7008909 -2.108204 ]]
1 3.3179946 [[ 0.7288167   0.7153621  -1.1801533 ]
 [-0.57753736 -0.1298833   1.6072978 ]
 [ 0.48373488 -0.51433605 -2.02127   ]]
2 2.0218027 [[ 0.66219085  0.7479632  -1.1461285 ]
 [-0.81948906  0.03000023  1.689366  ]
 [ 0.23214607 -0.33772916 -1.9462881 ]]
3 1.9710883 [[ 0.6434203   0.74127686 -1.1206716 ]
 [-0.8116129  -0.00900115  1.7204912 ]
 [ 0.20866647 -0.35079566 -1.909742  ]]
4 1.9446774 [[ 0.6235322   0.7400824  -1.099589  ]
 [-0.80967706 -0.01636278  1.725917  ]
 [ 0.17870612 -0.3366575  -1.8939198 ]]
5 1.923567 [[ 0.6073311   0.7366499  -1.0799555 ]
 [-0.79007834 -0.03363194  1.7235874 ]
 [ 0.16691466 -0.3340635  -1.8847224 ]]
6 1.9035923 [[ 0.5903174   0.7351024  -1.0613943 ]
 [-0.7749676  -0.04048849  1.7153332 ]
 [ 0.15076594 -0.322094   -1.8805432 ]]
7 1.8840802 [[ 0.5743792   0.7326286  -1.0429822 ]
 [-0.7552777  -0.05152     1.7066748 ]
 [ 0.13977

79 1.0776203 [[-0.3267705   0.52307487  0.06772117]
 [ 0.00271836 -0.12318436  1.0203438 ]
 [-0.2761403  -0.21317944 -1.5625511 ]]
80 1.0710086 [[-0.3361717   0.51997024  0.08022697]
 [ 0.00830221 -0.11999371  1.0115693 ]
 [-0.27857223 -0.21563864 -1.55766   ]]
81 1.0644722 [[-0.3455095   0.5168775   0.09265756]
 [ 0.0138215  -0.11677306  1.0028293 ]
 [-0.28096485 -0.2181255  -1.5527805 ]]
82 1.0580109 [[-0.3547848   0.513797    0.10501332]
 [ 0.0192775  -0.11352427  0.99412453]
 [-0.28331897 -0.22063816 -1.5479137 ]]
83 1.0516235 [[-0.3639983   0.5107292   0.11729462]
 [ 0.02467161 -0.11024932  0.98545545]
 [-0.2856352  -0.2231749  -1.5430607 ]]
84 1.0453093 [[-0.3731508   0.50767446  0.12950186]
 [ 0.03000497 -0.10695001  0.9768228 ]
 [-0.28791428 -0.22573394 -1.5382226 ]]
85 1.0390679 [[-0.38224304  0.5046331   0.14163542]
 [ 0.03527877 -0.10362817  0.96822715]
 [-0.2901568  -0.22831361 -1.5334003 ]]
86 1.0328984 [[-0.39127576  0.50160563  0.15369566]
 [ 0.04049423 -0.10028561  0.95

156 0.7495358 [[-0.90873533  0.33617026  0.8365905 ]
 [ 0.29648513  0.11611861  0.48727393]
 [-0.37093326 -0.39449567 -1.2864414 ]]
157 0.7471757 [[-0.9148408   0.3345386   0.8443277 ]
 [ 0.29885677  0.11837365  0.48264727]
 [-0.37105915 -0.39603263 -1.2847786 ]]
158 0.7448498 [[-0.92091787  0.3329269   0.8520164 ]
 [ 0.30119735  0.12059857  0.47808176]
 [-0.37115997 -0.3975422  -1.2831682 ]]
159 0.7425573 [[-0.92696667  0.33133507  0.85965705]
 [ 0.30350715  0.12279348  0.47357705]
 [-0.3712359  -0.39902452 -1.2816099 ]]
160 0.7402977 [[-0.9329876   0.32976294  0.86725   ]
 [ 0.3057864   0.12495846  0.4691328 ]
 [-0.37128717 -0.4004798  -1.2801033 ]]
161 0.73807037 [[-0.9389808   0.32821044  0.87479573]
 [ 0.30803528  0.1270937   0.46474868]
 [-0.37131408 -0.40190813 -1.2786481 ]]
162 0.73587483 [[-0.94494665  0.3266774   0.8822946 ]
 [ 0.31025413  0.12919918  0.46042436]
 [-0.37131673 -0.4033099  -1.2772437 ]]
163 0.7337104 [[-0.95088536  0.32516375  0.8897469 ]
 [ 0.31244302  0.1312