In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable(tf.random_normal([784, 200], stddev = 0.35))

In [3]:
y = tf.Variable(x.initialized_value() + 3.)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.


In [4]:
init_op = tf.global_variables_initializer()

In [5]:
sess = tf.Session()

In [6]:
sess.run(init_op)

In [7]:
print(sess.run(y))

[[3.4743972 3.3910058 2.4038074 ... 3.105155  3.0411286 3.1689923]
 [2.863661  3.8515077 2.7729256 ... 2.9064732 2.7155383 2.7301006]
 [3.378005  2.720343  2.927227  ... 3.6112165 3.2448034 2.796306 ]
 ...
 [2.2778995 3.2790103 2.3780618 ... 2.6375656 3.4825284 3.3377306]
 [3.1542687 3.3664625 2.9052925 ... 3.3966932 2.8044765 3.0655472]
 [3.4080243 2.890178  2.6867273 ... 3.4200585 3.507232  3.229082 ]]


In [8]:
print(y.get_shape())

(784, 200)
